name: CI

on:
  #when pull-request created to develop run workflow
  pull_request:
    branches: [ develop, master ]
  #when pushed to develop run workflow
  push:
    branches: [ develop, master ]
env:
  REGISTRY: home.nexus.com:8085
  IMAGE: thanujtk/react-app

jobs:
  build:
    runs-on: [ self-hosted ]
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cache node_modules
        uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "12.x"
      - run: npm ci
      #- run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage As Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test-coverage
          path: coverage
      - name: Build Project
        if: github.event_name == 'push'
        run: |
          npm run build
      - name: Upload Build Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-artifact
          path: build

      - name: Build Docker Image
        run: |
          npm run build
          docker build . -t ${{env.IMAGE}}

      - name: ZIP Release of Assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          zip -r build-artifact.zip ./build
          zip -r test-coverage.zip ./coverage
      #      - uses: actions/download-artifact@v2.0.10
      - name: Create a release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Deploy to Staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: npx surge --project ./build --domain thanujtk.surge.sh
        # Above needs surge token,  defined at jobs level as environment variable
      - name: Deploy to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx surge --project ./build --domain thanujtk.surge.sh
        # Above needs surge token,  defined at jobs level as environment variable
      #      - name: Docker Login Using Docker CLI
      #        id: login-dockerhub
      #        run: |
      #          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      #      - name: Docker Logout
      #        run: |
      #          docker logout ${{ steps.login-dockerhub.outputs.registry }}
      - name: Docker Login
        id: login-dockerhome
        uses: docker/login-action@v1.10.0
        with:
          registry: home.nexus.com:8085
          username: ${{ secrets.DOCKERHOME_USERNAME }}
          password: ${{ secrets.DOCKERHOME_TOKEN }}
      - name: Docker Logout
        run: |
          echo "${{ steps.login-dockerhome.outputs.registry }}"
          docker logout ${{ steps.login-dockerhome.outputs.registry }}